kernel:
    resource: ../src/Kernel.php
    type: annotation

homepage:
    path: /
    controller: App\Controller\DefaultController::home

movie_details:
    path: /movie/{movieId}
    controller: App\Controller\MovieController::details

movies_by_genre:
    path: /movies/{genreName}/{genreId}
    controller: App\Controller\GenreController::movies

movie_search:
    path: /search
    controller: App\Controller\MovieController::search

