kernel:
    resource: ../src/Kernel.php
    type: annotation

homepage:
    path: /
    controller: App\Controller\DefaultController::home
    options:
        expose: true

movie_details:
    path: /movie/{movieId}
    controller: App\Controller\MovieController::details
    options:
        expose: true

search:
    path: /search/{search}
    controller: App\Controller\DefaultController::search
    options:
        expose: true
